
local colors = require("tonada.colors").palette
local M = {}

M.groups = {
  "ColorColumn",                          { bg = colors.carbon, fg = colors.NONE },
  "Conceal",                              { bg = colors.NONE, fg = colors.NONE },
  "Cursor",                               { bg = colors.lavender, fg = colors.chaos_black },
  "CursorColumn",                         { bg = colors.dynamic_black , fg = colors.NONE },
  "CursorLine",                           { bg = colors.carbon, fg = colors.NONE },
  "Directory",                            { bg = colors.gentle_blue, fg = colors.NONE },
  "DiffAdd",                              { bg = colors.NONE, fg = colors.green },
  "DiffChange",                           { bg = colors.NONE, fg = colors.nickel },
  "DiffDelete",                           { bg = colors.NONE, fg = colors.red },
  "DiffText",                             { bg = colors.lead, fg = colors.white },
  "EndOfBuffer",                          { bg = colors.NONE, fg = colors.lead },
  "ErrorMsg",                             { bg = colors.NONE, fg = colors.light_pink },
  "VertSplit",                            { bg = colors.NONE, fg = colors.carbon },
  "Folded",                               { bg = colors.lead, fg = colors.nickel },
  "FoldColumn",                           { bg = colors.NONE, fg = colors.NONE },
  "SignColumn",                           { bg = colors.NONE, fg = colors.nickel },
  "IncSearch",                            { bg = colors.silver, fg = colors.dynamic_black },
  "Substitute",                           { bg = colors.weldon, fg = colors.dynamic_black },
  "LineNr",                               { bg = colors.NONE, fg = colors.arsenic },
  "CursorLineNr",                         { bg = colors.NONE, fg = colors.white },
  "CursorLineFold",                       { bg = colors.lead, fg = colors.nickel },
  "CursorLineSign",                       { bg = colors.NONE, fg = colors.onyx },
  "MatchWord",                            { bg = colors.arsenic, fg = colors.white },
  "MatchParen",                           { link = "MatchWord" },
  "ModeMsg",                              { bg = colors.NONE, fg = colors.light_slate },
  "MsgArea",                              { bg = colors.NONE, fg = colors.light_slate },
  "MoreMsg",                              { bg = colors.NONE, fg = colors.light_slate },
  "Normal",                               { bg = colors.lead, fg = colors.lavender },
  "NormalFloat",                          { bg = colors.dynamic_black, fg = colors.NONE },
  "FloatBorder",                          { bg = colors.NONE, fg = colors.blue },
  "FloatTitle",                           { bg = colors.arsenic, fg = colors.white },
  "NormalNC",                             { bg = colors.NONE, fg = colors.NONE },
  "Pmenu",                                { bg = colors.raisin, fg = colors.NONE },
  "PmenuSel",                             { bg = colors.weldon, fg = colors.chaos_black },
  "PmenuSbar",                            { bg = colors.raisin, fg = colors.NONE },
  "PmenuThumb",                           { bg = colors.arsenic, fg = colors.NONE },
  "Question",                             { bg = colors.NONE, fg = colors.gentle_blue },
  "QuickFixLine",                         { bg = colors.dynamic_black, fg = colors.NONE },
  "Search",                               { bg = colors.weldon, fg = colors.dynamic_black },
  "SpecialKey",                           { bg = colors.NONE, fg = colors.onyx },
  "StatusLine",                           { bg = colors.dynamic_black, fg = colors.NONE },
  "TabLineFill",                          { bg = colors.eerie_black, fg = colors.NONE },
  "Title",                                { bg = colors.NONE, fg = colors.gentle_blue  },
  "Visual",                               { bg = colors.onyx, fg = colors.NONE },
  "VisualNOS",                            { bg = colors.NONE, fg = colors.white_chocolate },
  "WarningMsg",                           { bg = colors.NONE, fg = colors.white_chocolate },
  "Winseparator",                         { bg = colors.NONE, fg = colors.carbon },
  "WildMenu",                             { bg = colors.weldon, fg = colors.white_chocolate },
  "WinBar",                               { bg = colors.NONE, fg = colors.NONE },
  "WinBarNC",                             { bg = colors.NONE, fg = colors.NONE },
  "Comment",                              { bg = colors.NONE, fg = colors.quartz },
  "Constant",                             { bg = colors.NONE, fg = colors.white_chocolate },
  "String",                               { bg = colors.NONE, fg = colors.light_blue },
  "Character",                            { bg = colors.NONE, fg = colors.light_blue },
  "Number",                               { bg = colors.NONE, fg = colors.purple },
  "Boolean",                              { bg = colors.NONE, fg = colors.purple },
  "Float",                                { bg = colors.NONE, fg = colors.purple },
  "Identifier",                           { bg = colors.NONE, fg = colors.lavender, sp = "none" },
  "Function",                             { bg = colors.NONE, fg = colors.gentle_blue },
  "Statement",                            { bg = colors.NONE, fg = colors.pastel_gray },
  "Conditional",                          { bg = colors.NONE, fg = colors.pastel_gray },
  "Repeat",                               { bg = colors.NONE, fg = colors.pastel_gray },
  "Label",                                { bg = colors.NONE, fg = colors.pastel_gray },
  "Operator",                             { bg = colors.NONE, fg = colors.orange, sp = "none" },
  "Keyword",                              { bg = colors.NONE, fg = colors.pastel_gray },
  "Exception",                            { bg = colors.NONE, fg = colors.white_chocolate },
  "PreProc",                              { bg = colors.NONE, fg = colors.weldon },
  "Include",                              { bg = colors.NONE, fg = colors.light_blue },
  "Define",                               { bg = colors.NONE, fg = colors.pastel_gray, sp = "none" },
  "Macro",                                { bg = colors.NONE, fg = colors.white_chocolate },
  "PreCondit",                            { bg = colors.NONE, fg = colors.white_chocolate },
  "Type",                                 { bg = colors.NONE, fg = colors.white_chocolate, sp = "none" },
  "StorageClass",                         { bg = colors.NONE, fg = colors.white_chocolate },
  "Structure",                            { bg = colors.NONE, fg = colors.white_chocolate },
  "Typedef",                              { bg = colors.NONE, fg = colors.white_chocolate },
  "Special",                              { bg = colors.NONE, fg = colors.gainsboro },
  "SpecialChar",                          { bg = colors.NONE, fg = colors.gentle_blue },
  "Tag",                                  { bg = colors.NONE, fg = colors.weldon },
  "Error",                                { bg = colors.white_chocolate, fg = colors.chaos_black },
  "Todo",                                 { bg = colors.dynamic_black, fg = colors.weldon },
  --********************
  -- NVIM-LSP
  --********************
  "LspReferenceText",                     { bg = colors.onyx, fg = colors.NONE },
  "LspReferenceRead",                     { bg = colors.onyx, fg = colors.NONE },
  "LspReferenceWrite",                    { bg = colors.onyx, fg = colors.NONE },
  "LspSignatureActiveParameter",          { bg = colors.light_blue, fg = colors.chaos_black },
  "DiagnosticError",                      { bg = colors.NONE, fg = colors.red },
  "DiagnosticWarn",                       { bg = colors.NONE, fg = colors.yellow },
  "DiagnosticInfo",                       { bg = colors.NONE, fg = colors.blue },
  "DiagnosticHint",                       { bg = colors.NONE, fg = colors.green },
  "DiagnosticOk",                         { bg = colors.NONE, fg = colors.purple},
  --********************
  -- TREESITTER
  --********************
  "@text.literal",                        { bg = colors.NONE, fg = colors.silver },
  "@text.reference",                      { bg = colors.NONE, fg = colors.lavender },
  "@text.title",                          { bg = colors.NONE, fg = colors.silver },
  "@text.uri",                            { bg = colors.NONE, fg = colors.silver },
  "@text.underline",                      { bg = colors.NONE, fg = colors.gentle_blue, underline = true },
  "@text.todo",                           { bg = colors.NONE, fg = colors.silver },
  "@comment",                             { bg = colors.NONE, fg = colors.quartz },
  "@punctuation",                         { bg = colors.NONE, fg = colors.gentle_blue },
  "@punctuation.delimiter",               { bg = colors.NONE, fg = colors.nickel },
  "@punctuation.bracket",                 { bg = colors.NONE, fg = colors.red },
  "@constant",                            { bg = colors.NONE, fg = colors.white_chocolate },
  "@constant.builtin",                    { bg = colors.NONE, fg = colors.purple },
  "@constant.macro",                      { bg = colors.NONE, fg = colors.white_chocolate },
  "@define",                              { bg = colors.NONE, fg = colors.white_chocolate },
  "@macro",                               { link = "Macro" },
  "@string",                              { bg = colors.NONE, fg = colors.light_blue },
  "@string.regex",                        { bg = colors.NONE, fg = colors.gainsboro },
  "@string.escape",                       { bg = colors.NONE, fg = colors.gainsboro },
  "@string.special",                      { bg = colors.NONE, fg = colors.gainsboro },
  "@character",                           { bg = colors.NONE, fg = colors.white_chocolate },
  "@character.special",                   { bg = colors.NONE, fg = colors.white_chocolate },
  "@number",                              { bg = colors.NONE, fg = colors.purple },
  "@boolean",                             { link = "Boolean" },
  "@float",                               { link = "Float" },
  "@function",                            { bg = colors.NONE, fg = colors.gentle_blue },
  "@function.call",                       { bg = colors.NONE, fg = colors.gentle_blue },
  "@function.builtin",                    { bg = colors.NONE, fg = colors.gentle_blue },
  "@function.macro",                      { bg = colors.NONE, fg = colors.white_chocolate },
  "@function.method",                     { bg = colors.NONE, fg = colors.gentle_blue },
  "@function.method.call",                { bg = colors.NONE, fg = colors.gentle_blue },
  "@parameter",                           { link = "Identifier" },
  "@method",                              { bg = colors.NONE, fg = colors.gentle_blue },
  "@field",                               { link = "Identifier" },
  "@property",                            { link = "Identifier" },
  "@constructor",                         { bg = colors.NONE, fg = colors.gainsboro },
  "@conditional",                         { link = "Conditional" },
  "@repeat",                              { link = "Repeat" },
  "@label",                               { link = "Label" },
  "@operator",                            { bg = colors.NONE, fg = colors.orange },
  "@keyword",                             { bg = colors.NONE, fg = colors.pastel_gray },
  "@keyword.return",                      { bg = colors.NONE, fg = colors.pastel_gray },
  "@exception",                           { bg = colors.NONE, fg = colors.white_chocolate },
  "@variable",                            { bg = colors.NONE, fg = colors.lavender },
  "@variable.parameter",                  { bg = colors.NONE, fg = colors.pastel_gray },
  "@variable.member",                     { bg = colors.NONE, fg = colors.blue },
  "@type",                                { bg = colors.NONE, fg = colors.blue },
  "@type.definition",                     { bg = colors.NONE, fg = colors.weldon },
  "@type.definition",                     { bg = colors.NONE, fg = colors.light_blue },
  "@module",                              { bg = colors.NONE, fg = colors.light_blue },
  "@storageclass",                        { link = "StorageClass"},
  "@structure",                           { link = "Structure"},
  "@namespace",                           { link = "Identifier"},
  "@include",                             { link = "Include"},
  --CPP
  --"@preproc",                           {},
  --"@debug",                             {},
  --"@tag",                               {},
  "@lsp.mod.constructorOrDestructor",     { bg = colors.NONE, fg = colors.pastel_gray },
  --********************
  -- NVIM-TREE
  --********************
  "NvimTreeEmptyFolderName",              { bg = colors.NONE, fg = colors.blue },
  "NvimTreeEndOfBuffer",                  { bg = colors.NONE, fg = colors.dynamic_black },
  "NvimTreeFolderIcon",                   { bg = colors.NONE, fg = colors.cardigan },
  "NvimTreeFolderName",                   { bg = colors.NONE, fg = colors.blue },
  "NvimTreeFolderArrowOpen",              { bg = colors.NONE, fg = colors.cardigan },
  "NvimTreeFolderArrowClosed",            { bg = colors.NONE, fg = colors.quartz },
  "NvimTreeGitDirty",                     { bg = colors.NONE, fg = colors.red },
  "NvimTreeNormal",                       { bg = colors.eerie_black, fg = colors.white },
  "NvimTreeNormalNC",                     { bg = colors.eerie_black, fg = colors.white },
  "NvimTreeOpenedFolderName",             { bg = colors.NONE, fg = colors.blue },
  "NvimTreeGitIgnored",                   { bg = colors.NONE, fg = colors.nickel },
  "NvimTreeIndentMarker",                 { bg = colors.NONE, fg = colors.carbon },
  --********************
  -- NAVIC
  --********************
  "NavicIconsConstant",                   { bg = colors.NONE, fg = colors.silver },
  "NavicIconsFunction",                   { bg = colors.NONE, fg = colors.gentle_blue },
  "NavicIconsIdentifier",                 { bg = colors.NONE, fg = colors.white_chocolate },
  "NavicIconsField",                      { bg = colors.NONE, fg = colors.white_chocolate },
  "NavicIconsVariable",                   { bg = colors.NONE, fg = colors.pastel_gray },
  "NavicIconsSnippet",                    { bg = colors.NONE, fg = colors.red },
  "NavicIconsText",                       { bg = colors.NONE, fg = colors.light_slate },
  "NavicIconsStructure",                  { bg = colors.NONE, fg = colors.pastel_gray },
  "NavicIconsType",                       { bg = colors.NONE, fg = colors.weldon },
  "NavicIconsKeyword",                    { bg = colors.NONE, fg = colors.gentle_blue },
  "NavicIconsMethod",                     { bg = colors.NONE, fg = colors.gentle_blue },
  "NavicIconsConstructor",                { bg = colors.NONE, fg = colors.blue },
  "NavicIconsFolder",                     { bg = colors.NONE, fg = colors.gentle_blue },
  "NavicIconsModule",                     { bg = colors.NONE, fg = colors.weldon },
  "NavicIconsProperty",                   { bg = colors.NONE, fg = colors.white_chocolate },
  "NavicIconsEnum",                       { bg = colors.NONE, fg = colors.blue },
  "NavicIconsUnit",                       { bg = colors.NONE, fg = colors.pastel_gray },
  "NavicIconsClass",                      { bg = colors.NONE, fg = colors.rackley },
  "NavicIconsFile",                       { bg = colors.NONE, fg = colors.gentle_blue },
  "NavicIconsInterface",                  { bg = colors.NONE, fg = colors.green },
  "NavicIconsColor",                      { bg = colors.NONE, fg = colors.white },
  "NavicIconsReference",                  { bg = colors.NONE, fg = colors.lavender },
  "NavicIconsEnumMember",                 { bg = colors.NONE, fg = colors.purple },
  "NavicIconsStruct",                     { bg = colors.NONE, fg = colors.pastel_gray },
  "NavicIconsValue",                      { bg = colors.NONE, fg = colors.cyan },
  "NavicIconsEvent",                      { bg = colors.NONE, fg = colors.yellow },
  "NavicIconsOperator",                   { bg = colors.NONE, fg = colors.lavender },
  "NavicIconsTypeParameter",              { bg = colors.NONE, fg = colors.white_chocolate },
  "NavicIconsNamespace",                  { bg = colors.NONE, fg = colors.rackley },
  "NavicIconsPackage",                    { bg = colors.NONE, fg = colors.green },
  "NavicIconsString",                     { bg = colors.NONE, fg = colors.green },
  "NavicIconsNumber",                     { bg = colors.NONE, fg = colors.pink },
  "NavicIconsBoolean",                    { bg = colors.NONE, fg = colors.orange },
  "NavicIconsArray",                      { bg = colors.NONE, fg = colors.blue },
  "NavicIconsObject",                     { bg = colors.NONE, fg = colors.pastel_gray },
  "NavicIconsKey",                        { bg = colors.NONE, fg = colors.red },
  "NavicIconsNull",                       { bg = colors.NONE, fg = colors.cyan },
  "NavicText",                            { bg = colors.NONE, fg = colors.lavender },
  "NavicSeparator",                       { bg = colors.NONE, fg = colors.red },
  --********************
  -- NVIM-CMP
  --********************
  "CmpItemAbbr",                          { bg = colors.NONE, fg = colors.white },
  "CmpItemAbbrMatch",                     { bg = colors.NONE, fg = colors.blue, bold = true },
  "CmpDoc",                               { bg = colors.chaos_black, fg = colors.NONE },
  "CmpDocBorder",                         { bg = colors.NONE, fg = colors.quartz },
  "CmpPmenu",                             { bg = colors.chaos_black, fg = colors.NONE },
  "CmpSel",                               { link = "PmenuSel", bold = true },
  "CmpItemKindConstant",                  { bg = colors.NONE, fg = colors.silver },
  "CmpItemKindFunction",                  { bg = colors.NONE, fg = colors.gentle_blue },
  "CmpItemKindIdentifier",                { bg = colors.NONE, fg = colors.white_chocolate },
  "CmpItemKindField",                     { bg = colors.NONE, fg = colors.white_chocolate },
  "CmpItemKindVariable",                  { bg = colors.NONE, fg = colors.pastel_gray },
  "CmpItemKindSnippet",                   { bg = colors.NONE, fg = colors.red },
  "CmpItemKindText",                      { bg = colors.NONE, fg = colors.light_slate },
  "CmpItemKindStructure",                 { bg = colors.NONE, fg = colors.pastel_gray },
  "CmpItemKindType",                      { bg = colors.NONE, fg = colors.weldon },
  "CmpItemKindKeyword",                   { bg = colors.NONE, fg = colors.gentle_blue },
  "CmpItemKindMethod",                    { bg = colors.NONE, fg = colors.gentle_blue },
  "CmpItemKindConstructor",               { bg = colors.NONE, fg = colors.blue },
  "CmpItemKindFolder",                    { bg = colors.NONE, fg = colors.gentle_blue },
  "CmpItemKindModule",                    { bg = colors.NONE, fg = colors.weldon },
  "CmpItemKindProperty",                  { bg = colors.NONE, fg = colors.white_chocolate },
  "CmpItemKindEnum",                      { bg = colors.NONE, fg = colors.blue },
  "CmpItemKindUnit",                      { bg = colors.NONE, fg = colors.pastel_gray },
  "CmpItemKindClass",                     { bg = colors.NONE, fg = colors.blue },
  "CmpItemKindFile",                      { bg = colors.NONE, fg = colors.gentle_blue },
  "CmpItemKindInterface",                 { bg = colors.NONE, fg = colors.green },
  "CmpItemKindColor",                     { bg = colors.NONE, fg = colors.white },
  "CmpItemKindReference",                 { bg = colors.NONE, fg = colors.lavender },
  "CmpItemKindEnumMember",                { bg = colors.NONE, fg = colors.purple },
  "CmpItemKindStruct",                    { bg = colors.NONE, fg = colors.pastel_gray },
  "CmpItemKindValue",                     { bg = colors.NONE, fg = colors.cyan },
  "CmpItemKindEvent",                     { bg = colors.NONE, fg = colors.yellow },
  "CmpItemKindOperator",                  { bg = colors.NONE, fg = colors.lavender },
  "CmpItemKindTypeParameter",             { bg = colors.NONE, fg = colors.white_chocolate },
  "CmpItemKindCopilot",                   { bg = colors.NONE, fg = colors.green },
  "CmpItemKindCodeium",                   { bg = colors.NONE, fg = colors.green },
  "CmpItemKindTabNine",                   { bg = colors.NONE, fg = colors.light_pink },
  "CmpItemKindSuperMaven",                { bg = colors.NONE, fg = colors.yellow },
  --********************
  -- BLINK-CMP
  --********************
  "BlinkCmpKindConstant",                  { bg = colors.NONE, fg = colors.silver },
  "BlinkCmpKindFunction",                  { bg = colors.NONE, fg = colors.gentle_blue },
  "BlinkCmpKindIdentifier",                { bg = colors.NONE, fg = colors.white_chocolate },
  "BlinkCmpKindField",                     { bg = colors.NONE, fg = colors.white_chocolate },
  "BlinkCmpKindVariable",                  { bg = colors.NONE, fg = colors.pastel_gray },
  "BlinkCmpKindSnippet",                   { bg = colors.NONE, fg = colors.red },
  "BlinkCmpKindText",                      { bg = colors.NONE, fg = colors.light_slate },
  "BlinkCmpKindStructure",                 { bg = colors.NONE, fg = colors.pastel_gray },
  "BlinkCmpKindType",                      { bg = colors.NONE, fg = colors.weldon },
  "BlinkCmpKindKeyword",                   { bg = colors.NONE, fg = colors.gentle_blue },
  "BlinkCmpKindMethod",                    { bg = colors.NONE, fg = colors.gentle_blue },
  "BlinkCmpKindConstructor",               { bg = colors.NONE, fg = colors.blue },
  "BlinkCmpKindFolder",                    { bg = colors.NONE, fg = colors.gentle_blue },
  "BlinkCmpKindModule",                    { bg = colors.NONE, fg = colors.weldon },
  "BlinkCmpKindProperty",                  { bg = colors.NONE, fg = colors.white_chocolate },
  "BlinkCmpKindEnum",                      { bg = colors.NONE, fg = colors.blue },
  "BlinkCmpKindUnit",                      { bg = colors.NONE, fg = colors.pastel_gray },
  "BlinkCmpKindClass",                     { bg = colors.NONE, fg = colors.rackley },
  "BlinkCmpKindFile",                      { bg = colors.NONE, fg = colors.gentle_blue },
  "BlinkCmpKindInterface",                 { bg = colors.NONE, fg = colors.green },
  "BlinkCmpKindColor",                     { bg = colors.NONE, fg = colors.white },
  "BlinkCmpKindReference",                 { bg = colors.NONE, fg = colors.lavender },
  "BlinkCmpKindEnumMember",                { bg = colors.NONE, fg = colors.purple },
  "BlinkCmpKindStruct",                    { bg = colors.NONE, fg = colors.pastel_gray },
  "BlinkCmpKindValue",                     { bg = colors.NONE, fg = colors.cyan },
  "BlinkCmpKindEvent",                     { bg = colors.NONE, fg = colors.yellow },
  "BlinkCmpKindOperator",                  { bg = colors.NONE, fg = colors.lavender },
  "BlinkCmpKindTypeParameter",             { bg = colors.NONE, fg = colors.white_chocolate },
  "BlinkCmpKindCopilot",                   { bg = colors.NONE, fg = colors.green },
  --********************
  -- TELESCOPE
  --********************
  "TelescopeNormal",                      { bg = colors.raisin, fg = colors.lavender },
  "TelescopeSelection",                   { bg = colors.carbon, fg = colors.white },
  "TelescopeMatching",                    { bg = colors.raisin, fg = colors.blue },
  "TelescopePromptBorder",                { bg = colors.onyx, fg = colors.onyx },
  "TelescopePromptNormal",                { bg = colors.onyx, fg = colors.lavender },
  "TelescopePromptPrefix",                { bg = colors.lead, fg = colors.red },
  "TelescopePreviewBorder",               { bg = colors.raisin, fg = colors.raisin },
  "TelescopePreviewTitle",                { bg = colors.green, fg = colors.chaos_black },
  "TelescopePromptTitle",                 { bg = colors.red, fg = colors.chaos_black },
  "TelescopeResultsBorder",               { bg = colors.raisin, fg = colors.raisin },
  "TelescopeResultsDiffAdd",              { bg = colors.NONE, fg = colors.green },
  "TelescopeResultsDiffChange",           { bg = colors.NONE, fg = colors.yellow },
  "TelescopeResultsDiffDelete",           { bg = colors.NONE, fg = colors.red },
  --********************
  -- NOTIFY
  --********************
  "NotifyBackground",                     { bg = colors.raisin, fg = colors.gainsboro },
  "NotifyERRORBorder",                    { bg = colors.NONE, fg = colors.red },
  "NotifyERRORIcon",                      { bg = colors.NONE, fg = colors.red },
  "NotifyERRORTitle",                     { bg = colors.NONE, fg = colors.red },
  "NotifyWARNBorder",                     { bg = colors.NONE, fg = colors.orange },
  "NotifyWARNIcon",                       { bg = colors.NONE, fg = colors.orange },
  "NotifyWARNTitle",                      { bg = colors.NONE, fg = colors.orange },
  "NotifyINFOBorder",                     { bg = colors.NONE, fg = colors.green },
  "NotifyINFOIcon",                       { bg = colors.NONE, fg = colors.green },
  "NotifyINFOTitle",                      { bg = colors.NONE, fg = colors.green },
  "NotifyDEBUGBorder",                    { bg = colors.NONE, fg = colors.arsenic },
  "NotifyDEBUGIcon",                      { bg = colors.NONE, fg = colors.arsenic },
  "NotifyDEBUGTitle",                     { bg = colors.NONE, fg = colors.arsenic },
  "NotifyTRACEBorder",                    { bg = colors.NONE, fg = colors.purple },
  "NotifyTRACEIcon",                      { bg = colors.NONE, fg = colors.purple },
  "NotifyTRACETitle",                     { bg = colors.NONE, fg = colors.purple },
  --********************
  -- NEOGIT
  --********************
  "NeogitTagName",                        { bg = colors.NONE, fg = colors.yellow },
  "NeogitTagDistance",                    { bg = colors.NONE, fg = colors.cyan },
  "NeogitFloatHeader",                    { bg = colors.eerie_black, fg = colors.lavender },
  "NeogitFloatHeaderHighlight",           { bg = colors.dynamic_black, fg = colors.cyan },
  --********************
  -- BARBAR
  --********************
  "BufferCurrent",                        { bg = colors.lead, fg = colors.white },
  "BufferCurrentIndex",                   { bg = colors.lead, fg = colors.white },
  "BufferCurrentMod",                     { bg = colors.lead, fg = colors.white_chocolate },
  "BufferCurrentModBtn",                  { bg = colors.lead, fg = colors.white_chocolate },
  "BufferCurrentSign",                    { bg = colors.lead, fg = colors.light_blue },
  "BufferCurrentTarget",                  { bg = colors.lead, fg = colors.dark_purple },
  "BufferCurrentIcon",                    { bg = colors.lead, fg = colors.NONE },
  "BufferCurrentERROR",                   { bg = colors.lead, fg = colors.red },
  "BufferCurrentWARN",                    { bg = colors.lead, fg = colors.yellow },
  "BufferCurrentINFO",                    { bg = colors.lead, fg = colors.blue },
  "BufferCurrentHINT",                    { bg = colors.lead, fg = colors.green },
  "BufferCurrentADDED",                   { bg = colors.lead, fg = colors.green },
  "BufferCurrentCHANGED",                 { bg = colors.lead, fg = colors.nickel },
  "BufferCurrentDELETED",                 { bg = colors.lead, fg = colors.red },
  "BufferVisible",                        { bg = colors.lead, fg = colors.silver },
  "BufferVisibleIndex",                   { bg = colors.lead, fg = colors.silver },
  "BufferVisibleMod",                     { bg = colors.lead, fg = colors.white_chocolate },
  "BufferVisibleModBtn",                  { bg = colors.lead, fg = colors.white_chocolate },
  "BufferVisibleSign",                    { bg = colors.lead, fg = colors.lead },
  "BufferVisibleTarget",                  { bg = colors.lead, fg = colors.dark_purple },
  "BufferVisibleIcon",                    { bg = colors.lead, fg = colors.NONE },
  "BufferVisibleERROR",                   { bg = colors.lead, fg = colors.red },
  "BufferVisibleWARN",                    { bg = colors.lead, fg = colors.yellow },
  "BufferVisibleINFO",                    { bg = colors.lead, fg = colors.blue },
  "BufferVisibleHINT",                    { bg = colors.lead, fg = colors.green },
  "BufferVisibleADDED",                   { bg = colors.lead, fg = colors.green },
  "BufferVisibleCHANGED",                 { bg = colors.lead, fg = colors.nickel },
  "BufferVisibleDELETED",                 { bg = colors.lead, fg = colors.red },
  "BufferInactive",                       { bg = colors.eerie_black, fg = colors.granite },
  "BufferInactiveIndex",                  { bg = colors.eerie_black, fg = colors.granite },
  "BufferInactiveMod",                    { bg = colors.eerie_black, fg = colors.white_chocolate },
  "BufferInactiveModBtn",                 { bg = colors.eerie_black, fg = colors.white_chocolate },
  "BufferInactiveSign",                   { bg = colors.eerie_black, fg = colors.eerie_black },
  "BufferInactiveTarget",                 { bg = colors.eerie_black, fg = colors.dark_purple },
  "BufferInactiveIcon",                   { bg = colors.eerie_black, fg = colors.granite },
  "BufferInactiveERROR",                  { bg = colors.eerie_black, fg = colors.red },
  "BufferInactiveWARN",                   { bg = colors.eerie_black, fg = colors.yellow },
  "BufferInactiveINFO",                   { bg = colors.eerie_black, fg = colors.blue },
  "BufferInactiveHINT",                   { bg = colors.eerie_black, fg = colors.green },
  "BufferInactiveADDED",                  { bg = colors.eerie_black, fg = colors.green },
  "BufferInactiveCHANGED",                { bg = colors.eerie_black, fg = colors.nickel },
  "BufferInactiveDELETED",                { bg = colors.eerie_black, fg = colors.red },
  "BufferTabpages",                       { bg = colors.eerie_black, fg = colors.silver },
  "BufferTabpageFill",                    { bg = colors.eerie_black, fg = colors.NONE },
  "BufferOffset",                         { bg = colors.eerie_black, fg = colors.NONE }
}

return M
